name: alaa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cached_network_image: ^3.0.0
  country_code_picker: ^2.0.2
  country_list_pick: ^1.0.1+6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  intl_phone_number_input: any
  path: ^1.9.0
  path_provider: ^2.1.2
  smooth_page_indicator: any
  sqflite: ^2.3.3
  video_player: ^2.1.6
  youtube_player_flutter: ^9.0.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0

dev_dependencies:
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter_lints: ^3.0.0
  flutter_screenutil: ^5.9.0
  flutter_test:
    sdk: flutter
  get_it: ^7.7.0
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
