// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyEY2x6b4QsZnwCJV7OBZtyYS1TaHbSo',
    appId: '1:612029760950:web:5879f86eabb55d2950ad17',
    messagingSenderId: '612029760950',
    projectId: 'technovers-95e2e',
    authDomain: 'technovers-95e2e.firebaseapp.com',
    storageBucket: 'technovers-95e2e.appspot.com',
    measurementId: 'G-826Q11N1T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrgwK6OFSXERz7oouJbWeb0v2_LxCpuRg',
    appId: '1:612029760950:android:62924179115539d650ad17',
    messagingSenderId: '612029760950',
    projectId: 'technovers-95e2e',
    storageBucket: 'technovers-95e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tr09jSJG0IU3SAoIzPmb7pyj1vFz3xo',
    appId: '1:612029760950:ios:5bd832a8bc3eb9b550ad17',
    messagingSenderId: '612029760950',
    projectId: 'technovers-95e2e',
    storageBucket: 'technovers-95e2e.appspot.com',
    androidClientId: '612029760950-938mvssa8e8of8j8ddkrhmit79pjp6bn.apps.googleusercontent.com',
    iosClientId: '612029760950-e5vkjkvciih59qsom2tdf3mrsc8nho0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.alaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tr09jSJG0IU3SAoIzPmb7pyj1vFz3xo',
    appId: '1:612029760950:ios:5bd832a8bc3eb9b550ad17',
    messagingSenderId: '612029760950',
    projectId: 'technovers-95e2e',
    storageBucket: 'technovers-95e2e.appspot.com',
    androidClientId: '612029760950-938mvssa8e8of8j8ddkrhmit79pjp6bn.apps.googleusercontent.com',
    iosClientId: '612029760950-e5vkjkvciih59qsom2tdf3mrsc8nho0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.alaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyEY2x6b4QsZnwCJV7OBZtyYS1TaHbSo',
    appId: '1:612029760950:web:987af2e701ea86fb50ad17',
    messagingSenderId: '612029760950',
    projectId: 'technovers-95e2e',
    authDomain: 'technovers-95e2e.firebaseapp.com',
    storageBucket: 'technovers-95e2e.appspot.com',
    measurementId: 'G-BXMG7Y94TE',
  );
}
